# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

semibart_cpp <- function(iX, itrt, iy, sigma, sigdf, sigquant, kfac, power, base, meanb, sigb, ntree, ndpost, inumcut, iusequants, binary_offset, probitlink, verbose, printevery) {
    .Call('semibart_semibart_cpp', PACKAGE = 'semibart', iX, itrt, iy, sigma, sigdf, sigquant, kfac, power, base, meanb, sigb, ntree, ndpost, inumcut, iusequants, binary_offset, probitlink, verbose, printevery)
}

