# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('smmbart_rcpp_rcpp_hello_world', PACKAGE = 'smmbart_rcpp')
}

